[build]
command = "npm install --production=false --no-audit --no-fund --include=optional && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22.19.0"
NPM_CONFIG_OPTIONAL = "true"


