[build]
command = "npm install --legacy-peer-deps --include=optional && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22.19.0"
NPM_CONFIG_OPTIONAL = "true"
ROLLUP_SKIP_NODEJS_NATIVE = "false"


