[build]
# The project is inside the my-app subdirectory
base = "my-app"
# Use npm to install and build to ensure optional deps (like Rollup's) are installed
command = "npm run build"
# Vite outputs to dist by default
publish = "dist"

[build.environment]
# Align Node version with Netlify's environment (adjust if you use a different one)
NODE_VERSION = "22"

